/* ============================================================
         1. BANK SOAL
         ============================================================ */
const CATEGORY_META = {
  'K. Kerja': { icon: '🏃' },
  'K. Sifat': { icon: '✨' },
  'K. Benda': { icon: '📦' },
  'K. Keterangan': { icon: '⏱️' },
};

const QUESTION_BANK = {
  'K. Kerja': [
    {
      q: 'A: <ruby>田中<rt>たなか</rt></ruby>さん、<ruby>今日<rt>きょう</rt></ruby>いい<ruby>天気<rt>てんき</rt></ruby>ですね。<br>B: そうですね、どこかへ<ruby>行<rt>い</rt></ruby>きますか。<br>A: ええ、ちょっと<ruby>銀行<rt>ぎんこう</rt></ruby>へ<ruby>野菜<rt>やさい</rt></ruby>を<ruby>買<rt>か</rt></ruby>いに<ruby>行<rt>い</rt></ruby>きます。',
      options: ['membuang', 'berdiri', 'salah/berbeda', 'membantu', 'melepas pakaian'],
      answer: 'salah/berbeda',
    },

    { q: '<ruby>違<rt>ちが</rt></ruby>います', options: ['membuang', 'berdiri', 'salah/berbeda', 'membantu', 'melepas pakaian'], answer: 'salah/berbeda' },
    { q: '<ruby>起<rt>お</rt></ruby>きます', options: ['banguntidur', 'duduk', 'bertemu dengan', 'mengumpulkan', 'mengetahui'], answer: 'banguntidur' },
    { q: '<ruby>寝<rt>ね</rt></ruby>ます', options: ['membuka', 'mendaki', 'tidur', 'memanggil', 'menerima'], answer: 'tidur' },
    { q: '<ruby>働<rt>はた</rt></ruby>きます', options: ['turun', 'menghapus/mematikan', 'memeriksa', 'bekerja', 'makan'], answer: 'bekerja' },
    { q: '<ruby>休<rt>やす</rt></ruby>みます', options: ['melihat', 'istirahat/libur', 'lembur', 'teringat', 'membuang'], answer: 'istirahat/libur' },
    { q: '<ruby>勉強<rt>べんきょう</rt></ruby>します', options: ['mencuci', 'memeriksa', 'belajar', 'mengemudi', 'membuat'], answer: 'belajar' },
    { q: '<ruby>終<rt>お</rt></ruby>わります', options: ['membuat', 'menghentikan', 'selesai', 'pulang', 'berenang'], answer: 'selesai' },
    { q: '<ruby>行<rt>い</rt></ruby>きます', options: ['memesan', 'pergi', 'berenang', 'ada (benda mati)', 'pergi keluar'], answer: 'pergi' },
    { q: '<ruby>来<rt>き</rt></ruby>ます', options: ['meminjamkan', 'bernyanyi', 'mencuci', 'datang', 'belanja'], answer: 'datang' },
    { q: '<ruby>帰<rt>かえ</rt></ruby>ります', options: ['memulai', 'membawa pergi', 'menginap', 'belajar', 'pulang'], answer: 'pulang' },
    { q: '<ruby>食べ<rt>たべ</rt></ruby>ます', options: ['dinas luar kota', 'makan', 'memakai', 'menukar', 'mandi/shower'], answer: 'makan' },
    { q: '<ruby>飲<rt>の</rt></ruby>みます', options: ['mengerti', 'membayar', 'membawa datang', 'menutup', 'minum'], answer: 'minum' },
    { q: '<ruby>見<rt>み</rt></ruby>ます', options: ['membaca', 'melihat', 'menghentikan', 'menurunkan', 'salah/berbeda'], answer: 'melihat' },
    { q: '<ruby>聞<rt>き</rt></ruby>きます', options: ['menikah', 'menarik', 'mendengar/bertanya', 'berenang', 'selesai'], answer: 'mendengar/bertanya' },
    { q: '<ruby>読<rt>よみ</rt></ruby>ます', options: ['memanggil', 'membaca', 'bermain', 'belajar', 'pergi'], answer: 'membaca' },
    { q: '<ruby>書<rt>か</rt></ruby>きます', options: ['memasukkan', 'membersihkan', 'perlu', 'membuang', 'menulis'], answer: 'menulis' },
    { q: '<ruby>買<rt>か</rt></ruby>います', options: ['membawa', 'membeli', 'menelepon', 'meminjam', 'bekerja'], answer: 'membeli' },
    { q: '<ruby>取<rt>と</rt></ruby>ります', options: ['mengambil', 'meneliti', 'menunggu', 'berganti kendaraan', 'mengembalikan'], answer: 'mengambil' },
    { q: '<ruby>切<rt>き</rt></ruby>ります', options: ['menjadi', 'pergi', 'mencuci baju', 'memotong', 'masuk'], answer: 'memotong' },
    { q: '<ruby>送<rt>お</rt></ruby>ります', options: ['mencuci baju', 'mengirim', 'belajar', 'dinas luar kota', 'minum'], answer: 'mengirim' },
    { q: 'あげます', options: ['memberi', 'memotong', 'meminjamkan', 'memesan', 'bergegas'], answer: 'memberi' },
    { q: 'もらいます', options: ['menekan', 'menerima', 'membuat', 'menjual', 'membersihkan'], answer: 'menerima' },
    { q: '<ruby>貸<rt>か</rt></ruby>します', options: ['jalan-jalan', 'melepas pakaian', 'meminjamkan', 'membuka', 'menjemput'], answer: 'meminjamkan' },
    { q: '<ruby>借<rt>か</rt></ruby>ります', options: ['mengemudi', 'membawa datang', 'tinggal', 'meminjam', 'belajar'], answer: 'meminjam' },
    { q: '<ruby>教<rt>おし</rt></ruby>えます', options: ['melalui', 'mengajar', 'memanggil', 'menyimpan', 'studi wisata'], answer: 'mengajar' },
    { q: '<ruby>習<rt>なら</rt></ruby>います', options: ['bermain', 'mempelajari', 'studi wisata', 'duduk', 'memasukkan'], answer: 'mempelajari' },
    { q: '<ruby>電話<rt>でんわ</rt></ruby>をかけます', options: ['menelepon', 'mencuci baju', 'menekan', 'tinggal', 'turun'], answer: 'menelepon' },
    { q: '<ruby>分<rt>わ</rt></ruby>かります', options: ['mendengar/bertanya', 'lembur', 'membawa', 'mengerti', 'melupakan'], answer: 'mengerti' },
    { q: '<ruby>有<rt>あ</rt></ruby>ります/あります', options: ['memeriksa', 'mendengar/bertanya', 'ada ', 'membuat', 'menikah'], answer: 'ada ' },
    { q: '<ruby>い</rt></ruby>ます', options: ['mengembalikan', 'membuang', 'membuka', 'ada ', 'sudah menikah'], answer: 'ada ' },
    { q: '<ruby>遊<rt>あそ</rt></ruby>びます', options: ['berdiri', 'bermain', 'belanja', 'memancing', 'memakai'], answer: 'bermain' },
    { q: '<ruby>泳<rt>およ</rt></ruby>ぎます', options: ['berenang', 'menelepon', 'mengeluarkan', 'bernyanyi', 'mengingat'], answer: 'berenang' },
    { q: '<ruby>迎<rt>むか</rt></ruby>えます', options: ['berenang', 'menerima', 'membuang', 'menjemput', 'meminjam'], answer: 'menjemput' },
    { q: '<ruby>会<rt>あ</rt></ruby>います', options: ['ada ', 'menurunkan', 'bergegas', 'berbicara', 'bertemu'], answer: 'bertemu' },
    { q: '<ruby>疲<rt>つか</rt></ruby>れます', options: ['membeli', 'lelah', 'menghapus/mematikan', 'membersihkan', 'mencucibaju'], answer: 'lelah' },
    { q: '<ruby>結<rt>けっ</rt></ruby>婚します', options: ['menikah', 'memulai', 'memotret', 'melihat', 'tidur'], answer: 'menikah' },
    { q: '<ruby>食事<rt>しょくじ</rt></ruby>します', options: ['memakai', 'membaca', 'makan', 'studiwisata', 'membeli'], answer: 'makan' },
    { q: '<ruby>散歩<rt>さんぽ</rt></ruby>します', options: ['mengetahui', 'jalan-jalan', 'membaca', 'menulis', 'menjadi'], answer: 'jalan-jalan' },
    { q: '<ruby>釣<rt>つ</rt></ruby>りをします', options: ['memperbaiki', 'menunjukkan', 'memancing', 'menikah', 'membawa datang'], answer: 'memancing' },
    { q: '<ruby>消<rt>け</rt></ruby>します', options: ['mendaki', 'menukar', 'membantu', 'menghapus/mematikan', 'istirahat/libur'], answer: 'menghapus/mematikan' },
    { q: '<ruby>開<rt>あ</rt></ruby>けます', options: ['membuka', 'berenang', 'membersihkan', 'mengajar', 'mendengar/bertanya'], answer: 'membuka' },
    { q: '<ruby>閉<rt>し</rt></ruby>めます', options: ['bangun tidur', 'menutup', 'melupakan', 'jalan-jalan', 'meminjamkan'], answer: 'menutup' },
    {
      q: 'Khawatir',
      options: ['<ruby>掃除<rt>そうじ</rt></ruby>します ', '<ruby>調<rt>しら</rt></ruby> べます ', '<ruby>洗濯<rt>せんたく</rt></ruby>します ', '<ruby>心配<rt>しんぱい</rt></ruby>します ', 'もって<ruby>行<rt>い</rt></ruby>きます  '],
      answer: '<ruby>心配<rt>しんぱい</rt></ruby>します ',
    },
    { q: 'Lembur', options: ['もって行きます (もっていきます) ', '残業します (ざんぎょうします) ', '掃除します (そうじします) ', '予約します (よやくします) ', '掃除します (そうじします) '], answer: '残業します (ざんぎょうします) ' },
    {
      q: 'Dinas luar kota',
      options: [
        '<ruby>運<rt>うん</rt></ruby><ruby>転<rt>てん</rt></ruby>します (うんてんします) ',
        '<ruby>結<rt>けっ</rt></ruby>婚しています (けっこんしています) ',
        '要ります (いります) ',
        '出張します (しゅっちょうします) ',
        '残業します (ざんぎょうします) ',
      ],
      answer: '出張します (しゅっちょうします) ',
    },
    { q: 'Mencuci', options: ['出張します (しゅっちょうします) ', '登ります (のぼります) ', '洗います (あらいます) ', '捨てます (すてます) ', '集めます (あつめます) '], answer: '洗います (あらいます) ' },
    { q: 'Menarik', options: ['引きます (ひきます) ', '洗濯します (せんたくします) ', '集めます (あつめます) ', '洗います (あらいます) ', '出張します (しゅっちょうします) '], answer: '引きます (ひきます) ' },
    {
      q: 'Bernyanyi',
      options: ['<ruby>結<rt>けっ</rt></ruby>婚しています (けっこんしています) ', '洗います (あらいます) ', '引きます (ひきます) ', '<ruby>結<rt>けっ</rt></ruby>婚しています (けっこんしています) ', '歌います (うたいます) '],
      answer: '歌います (うたいます) ',
    },
    { q: 'Mengumpulkan', options: ['集めます (あつめます) ', '泊まります (とまります) ', '運転します (うんてんします) ', 'なります ', '引きます (ひきます) '], answer: '集めます (あつめます) ' },
    { q: 'Membuang', options: ['なります ', '残業します (ざんぎょうします) ', '予約します (よやくします) ', '捨てます (すてます) ', '調べます (しらべます) '], answer: '捨てます (すてます) ' },
    { q: 'Menukar', options: ['換えます (かえます) ', '歌います (うたいます) ', 'なります ', '洗濯します (せんたくします) ', '予約します (よやくします) '], answer: '換えます (かえます) ' },
    { q: 'Mengemudi', options: ['修理します (しゅうりします) ', '換えます (かえます) ', '調べます (しらべます) ', '集めます (あつめます) ', '運転します (うんてんします) '], answer: '運転します (うんてんします) ' },
  ],
  'K. Sifat': [
    { q: '大きい (おおきい)  ', options: [' pedas ', ' besar ', ' hitam ', ' sepi/tenang ', ' sederhana '], answer: ' besar ' },
    { q: ' 小さい (ちいさい)  ', options: [' dekat ', ' lambat ', ' kecil ', ' gelap ', ' luas '], answer: ' kecil ' },
    { q: ' 悪い (わるい) ', options: [' terkenal ', 'buruk ', ' baru ', ' jauh ', ' merah '], answer: 'buruk ' },
    { q: ' 新しい (あたらしい)  ', options: [' pendek ', ' tidak mahir ', ' sedikit ', ' baru ', ' penting '], answer: ' baru ' },
    { q: ' 古い (ふるい)  ', options: [' lama ', ' merah ', 'buruk ', ' dekat ', ' lambat '], answer: ' lama ' },
    { q: ' 悪い (わるい)  ', options: [' sakit ', ' jauh ', ' banyak ', ' pedas ', ' buruk '], answer: ' buruk ' },
    { q: ' 暑い (あつい)  ', options: [' besar ', ' panas ', ' gelap ', ' luas ', ' besar '], answer: ' panas ' },
    { q: ' 寒い (さむい)  ', options: [' tinggi/mahal ', ' murah ', ' dingin (cuaca) ', 'sulit ', ' baru '], answer: ' dingin (cuaca) ' },
    { q: ' 冷たい (つめたい)  ', options: [' dingin (sentuh) ', ' menarik ', ' bermacam-macam ', ' terang/ceria ', ' sehat '], answer: ' dingin (sentuh) ' },
    { q: ' 難しい (むずかしい)  ', options: [' senggang ', ' benci ', ' rendah ', ' sulit ', ' jauh '], answer: ' sulit ' },
    { q: ' 易しい (やさしい)  ', options: [' murah ', ' dingin (cuaca) ', ' mudah ', ' tinggi/mahal ', ' bermacam-macam '], answer: ' mudah ' },
    { q: ' 高い (たかい)  ', options: [' baru ', ' tinggi/mahal ', ' sempit ', ' terkenal ', ' ingin '], answer: ' tinggi/mahal ' },
    { q: ' 安い (やすい)  ', options: [' murah ', ' dekat ', ' luas ', ' sakit ', ' manis '], answer: ' murah ' },
    { q: ' 低い (ひくい)  ', options: [' muda ', ' rendah ', ' putih ', ' dingin (cuaca) ', ' mudah '], answer: ' rendah ' },
    { q: ' 忙しい (いそがしい)  ', options: [' mudah ', ' gelap ', 'panas ', ' merah ', ' sibuk '], answer: ' sibuk ' },
    { q: ' 楽しい (たのしい)  ', options: [' lama ', ' menyenangkan ', ' panas ', ' sejuk ', ' sibuk '], answer: ' menyenangkan ' },
    { q: ' 白い (しろい)  ', options: [' mengantuk ', ' menyenangkan ', ' putih ', ' panjang ', ' murah '], answer: ' putih ' },
    { q: ' 黒い (くろい)  ', options: [' hitam ', 'buruk ', ' jauh ', ' cepat/awal ', ' pedas '], answer: ' hitam ' },

    { q: ' Gelap ', options: [' 危ない (あぶない)  ', ' 暗い (くらい)  ', ' 元気(な) (げんき)  ', ' 親切(な) (しんせつ)  ', ' 痛い (いたい)  '], answer: ' 暗い (くらい)  ' },
    { q: ' Berbahaya ', options: [' 暗い (くらい)  ', ' 上手(な) (じょうず)  ', ' 弱い (よわい)  ', ' 危ない (あぶない)  ', ' 静か(な) (しずか)  '], answer: ' 危ない (あぶない)  ' },
    { q: ' Sakit ', options: [' 静か(な) (しずか)  ', ' 痛い (いたい)  ', ' 好き(な) (すき)  ', ' 眠い (ねむい)  ', ' 嫌い(な) (きらい)  '], answer: ' 痛い (いたい)  ' },
    { q: ' Menarik hati ', options: [' 弱い (よわい)  ', ' 面白い (おもしろい)  ', ' 下手(な) (へた)  ', ' 痛い (いたい)  ', ' 有名(な) (ゆうめい)  '], answer: ' 面白い (おもしろい)  ' },
    { q: ' Mengantuk ', options: [' 有名(な) (ゆうめい)  ', ' 強い (つよい)  ', ' 便利(な) (べんり)  ', ' 眠い (ねむい)  ', ' 下手(な) (へた)  '], answer: ' 眠い (ねむい)  ' },
    { q: ' Kuat ', options: [' 痛い (いたい)  ', ' 嫌い(な) (きらい)  ', ' 強い (つよい)  ', ' 有名(な) (ゆうめい)  ', ' 便利(な) (べんり)  '], answer: ' 強い (つよい)  ' },
    { q: ' Lemah ', options: [' 弱い (よわい)  ', ' 眠い (ねむい)  ', ' 強い (つよい)  ', ' 暗い (くらい)  ', ' 元気(な) (げんき)  '], answer: ' 弱い (よわい)  ' },
    { q: ' Sepi/Tenang ', options: [' 強い (つよい)  ', ' 有名(な) (ゆうめい)  ', ' 静か(な) (しずか)  ', ' 好き(な) (すき)  ', ' 親切(な) (しんせつ)  '], answer: ' 静か(な) (しずか)  ' },
    { q: ' Terkenal ', options: [' 有名(な) (ゆうめい)  ', ' 元気(な) (げんき)  ', ' 面白い (おもしろい)  ', ' 上手(な) (じょうず)  ', ' 暇(な) (ひま)  '], answer: ' 有名(な) (ゆうめい)  ' },
    { q: ' Baik hati ', options: [' 上手(な) (じょうず)  ', ' 親切(な) (しんせつ)  ', ' 嫌い(な) (きらい)  ', ' 下手(な) (へた)  ', ' 暗い (くらい)  '], answer: ' 親切(な) (しんせつ)  ' },
    { q: ' Sehat ', options: [' 眠い (ねむい)  ', ' 弱い (よわい)  ', ' 静か(な) (しずか)  ', ' 強い (つよい)  ', ' 元気(な) (げんき)  '], answer: ' 元気(な) (げんき)  ' },
    { q: ' Senggang ', options: [' 好き(な) (すき)  ', ' 面白い (おもしろい)  ', ' 眠い (ねむい)  ', ' 静か(な) (しずか)  ', ' 暇(な) (ひま)  '], answer: ' 暇(な) (ひま)  ' },
    { q: ' Praktis ', options: [' 嫌い(な) (きらい)  ', ' 危ない (あぶない)  ', ' 便利(な) (べんり)  ', ' 元気(な) (げんき)  ', ' 面白い (おもしろい)  '], answer: ' 便利(な) (べんり)  ' },
    { q: ' Suka ', options: [' 面白い (おもしろい)  ', ' 暗い (くらい)  ', ' 親切(な) (しんせつ)  ', ' 嫌い(な) (きらい)  ', ' 好き(な) (すき)  '], answer: ' 好き(な) (すき)  ' },
  ],
  'K. Benda': [
    { q: '「学校 (がっこう)」', options: ['Sekolah', 'Rumah Sakit', 'Pasar', 'Kantor', 'Stasiun'], answer: 'Sekolah' },
    { q: '「先生 (せんせい)」', options: ['Murid', 'Guru', 'Dokter', 'Polisi', 'Petani'], answer: 'Guru' },
    { q: '「本 (ほん)」', options: ['Buku', 'Pena', 'Meja', 'Kursi', 'Tas'], answer: 'Buku' },
    { q: '「猫 (ねこ)」', options: ['Anjing', 'Kucing', 'Burung', 'Ikan', 'Kuda'], answer: 'Kucing' },
    { q: '「犬 (いぬ)」', options: ['Kucing', 'Anjing', 'Kelinci', 'Sapi', 'Ayam'], answer: 'Anjing' },
    { q: '「水 (みず)」', options: ['Api', 'Air', 'Tanah', 'Angin', 'Es'], answer: 'Air' },
    { q: '「家 (いえ)」', options: ['Rumah', 'Sekolah', 'Toko', 'Taman', 'Jembatan'], answer: 'Rumah' },
    { q: '「車 (くるま)」', options: ['Sepeda', 'Mobil', 'Kereta', 'Pesawat', 'Kapal'], answer: 'Mobil' },
  ],
  'K. Keterangan': [
    { q: '「とても 」', options: ['Sangat', 'Sedikit', 'Jarang', 'Kadang-kadang', 'Tidak pernah'], answer: 'Sangat' },
    { q: '「いつも 」', options: ['Selalu', 'Kadang-kadang', 'Jarang', 'Tidak pernah', 'Baru saja'], answer: 'Selalu' },
    { q: '「ゆっくり 」', options: ['Cepat', 'Perlahan', 'Tiba-tiba', 'Terus-menerus', 'Berulang kali'], answer: 'Perlahan' },
    { q: '「もう 」', options: ['Sudah', 'Belum', 'Masih', 'Akan', 'Sedang'], answer: 'Sudah' },
    { q: '「まだ 」', options: ['Sudah', 'Masih / Belum', 'Selalu', 'Jarang', 'Sering'], answer: 'Masih / Belum' },
    { q: '「よく」', options: ['Sering / Dengan baik', 'Jarang', 'Buruk', 'Salah', 'Benar'], answer: 'Sering / Dengan baik' },
  ],
};
const CATEGORIES = Object.keys(QUESTION_BANK);
